export const exampleTasks = [
  {
    id: "001",
    task: "Example Task 1",
    tag: "bug",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus architecto voluptas ipsam doloremque non qui quod consequuntur nulla explicabo accusantium?",
    priority: "low",
    status: "backlog",
  },
  {
    id: "002",
    task: "Example Task 2",
    tag: "fix",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus architecto voluptas ipsam doloremque non qui quod consequuntur nulla explicabo accusantium?",
    priority: "medium",
    status: "backlog",
  },
  {
    id: "003",
    task: "Example Task 3",
    tag: "feat",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus architecto voluptas ipsam doloremque non qui quod consequuntur nulla explicabo accusantium?",
    priority: "critical",
    status: "in progress",
  },
  {
    id: "004",
    task: "Example Task 4",
    tag: "bug",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus architecto voluptas ipsam doloremque non qui quod consequuntur nulla explicabo accusantium?",
    priority: "high",
    status: "completed",
  },
  {
    id: "005",
    task: "Example Task 5",
    tag: "feat",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus architecto voluptas ipsam doloremque non qui quod consequuntur nulla explicabo accusantium?",
    priority: "low",
    status: "cancelled",
  },
  {
    id: "006",
    task: "Example Task 6",
    tag: "bug",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus architecto voluptas ipsam doloremque non qui quod consequuntur nulla explicabo accusantium?",
    priority: "medium",
    status: "under review",
  },
] as const;