import type { Metadata } from "next";
import { Inter, M_PLUS_1_Code } from "next/font/google";
import "./globals.css";
import Container from "@/components/container";
import Header from "@/components/header";

const font = M_PLUS_1_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-neutral-950`}>
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
